name: Node CI and Build/Push to ECR

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  node-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm@10.9
        run: npm install -g npm@10.9

      - name: Install dependencies
        run: npm ci

      - name: Run dependency cruiser check
        run: npm run arch:check

      - name: Lint and build
        run: |
          npm run lint
          npm run build --if-present

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Check for vulnerabilities
        run: npm audit
